name: ioos_nems
channels:
    - conda-forge
    - mullenkamp
dependencies:
    - geojson
    - netCDF4
    - numba
    - numpy
    - pygc
    - ruamel.yaml
    - shapely
    - simplejson
    - xarray<2022.3.0
    - pandas
    - requests
    - bs4
    - lxml
    - gsw
    - ipywidgets
    - bokeh
    - ipydatetime
    - hilltop-py==1.5.0
    - ioos_qc
    # if conda version of ioos_qc behind pip can use pip
    #- pip:
    #  - ioos-qc